# Generated by Django 5.0.6 on 2024-08-07 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Task', models.CharField(max_length=100)),
                ('Desc', models.CharField(max_length=500)),
            ],
        ),
    ]
