# Generated by Django 5.0.6 on 2024-08-08 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('do', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='mark',
            field=models.IntegerField(default=0),
        ),
    ]
